[2025-01-24T21:41:00.259-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T21:41:00.291-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-24T21:41:00.309-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-24T21:41:00.310-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-24T21:41:00.359-0300] {taskinstance.py:2889} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2025-01-22 00:00:00+00:00
[2025-01-24T21:41:00.364-0300] {standard_task_runner.py:72} INFO - Started process 19819 to run task
[2025-01-24T21:41:00.371-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmp8tioxiud']
[2025-01-24T21:41:00.374-0300] {standard_task_runner.py:105} INFO - Job 6: Subtask twitter_datascience
[2025-01-24T21:41:00.513-0300] {task_command.py:467} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [running]> on host ANDERSON.
[2025-01-24T21:41:00.678-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TwitterDAG' AIRFLOW_CTX_TASK_ID='twitter_datascience' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-01-24T21:41:00.681-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-24T21:41:00.682-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-24T21:41:00.683-0300] {logging_mixin.py:190} INFO - Current task name:twitter_datascience state:running start_date:2025-01-25 00:41:00.292682+00:00
[2025-01-24T21:41:00.684-0300] {logging_mixin.py:190} INFO - Dag name:TwitterDAG and current dag run status:running
[2025-01-24T21:41:00.685-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T21:41:00.726-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-24T21:41:00.792-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-24T21:41:00.793-0300] {logging_mixin.py:190} INFO - Task start:2025-01-25 00:41:00.292682+00:00 end:2025-01-25 00:41:00.791909+00:00 duration:0.499227
[2025-01-24T21:41:00.794-0300] {logging_mixin.py:190} INFO - Task:<Task(TwitterOperator): twitter_datascience> dag:<DAG: TwitterDAG> dagrun:<DagRun TwitterDAG @ 2025-01-22 00:00:00+00:00: scheduled__2025-01-22T00:00:00+00:00, state:running, queued_at: 2025-01-25 00:40:34.312768+00:00. externally triggered: False>
[2025-01-24T21:41:00.795-0300] {logging_mixin.py:190} INFO - Failure caused by The conn_id `twitter_default` isn't defined
[2025-01-24T21:41:00.796-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_datascience, run_id=scheduled__2025-01-22T00:00:00+00:00, execution_date=20250122T000000, start_date=20250125T004100, end_date=20250125T004100
[2025-01-24T21:41:00.841-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T21:41:00.842-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task twitter_datascience (The conn_id `twitter_default` isn't defined; 19819)
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-24T21:41:00.907-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-24T21:41:00.940-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-24T21:41:00.967-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-25T00:12:43.170-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T00:12:43.197-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-25T00:12:43.214-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-25T00:12:43.215-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-25T00:12:43.263-0300] {taskinstance.py:2889} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2025-01-22 00:00:00+00:00
[2025-01-25T00:12:43.269-0300] {standard_task_runner.py:72} INFO - Started process 30918 to run task
[2025-01-25T00:12:43.275-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpcu47hi6h']
[2025-01-25T00:12:43.278-0300] {standard_task_runner.py:105} INFO - Job 10: Subtask twitter_datascience
[2025-01-25T00:12:43.390-0300] {task_command.py:467} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [running]> on host ANDERSON.
[2025-01-25T00:12:43.560-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TwitterDAG' AIRFLOW_CTX_TASK_ID='twitter_datascience' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-01-25T00:12:43.562-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-25T00:12:43.564-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-25T00:12:43.564-0300] {logging_mixin.py:190} INFO - Current task name:twitter_datascience state:running start_date:2025-01-25 03:12:43.198968+00:00
[2025-01-25T00:12:43.565-0300] {logging_mixin.py:190} INFO - Dag name:TwitterDAG and current dag run status:running
[2025-01-25T00:12:43.566-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T00:12:43.609-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T00:12:43.668-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-25T00:12:43.669-0300] {logging_mixin.py:190} INFO - Task start:2025-01-25 03:12:43.198968+00:00 end:2025-01-25 03:12:43.667529+00:00 duration:0.468561
[2025-01-25T00:12:43.670-0300] {logging_mixin.py:190} INFO - Task:<Task(TwitterOperator): twitter_datascience> dag:<DAG: TwitterDAG> dagrun:<DagRun TwitterDAG @ 2025-01-22 00:00:00+00:00: scheduled__2025-01-22T00:00:00+00:00, state:running, queued_at: 2025-01-25 03:12:03.564180+00:00. externally triggered: False>
[2025-01-25T00:12:43.671-0300] {logging_mixin.py:190} INFO - Failure caused by The conn_id `twitter_default` isn't defined
[2025-01-25T00:12:43.672-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_datascience, run_id=scheduled__2025-01-22T00:00:00+00:00, execution_date=20250122T000000, start_date=20250125T031243, end_date=20250125T031243
[2025-01-25T00:12:43.718-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T00:12:43.720-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task twitter_datascience (The conn_id `twitter_default` isn't defined; 30918)
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T00:12:43.854-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-25T00:12:43.911-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T00:12:43.936-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-25T11:41:21.308-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T11:41:21.343-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-25T11:41:21.362-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-25T11:41:21.364-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-25T11:41:21.425-0300] {taskinstance.py:2889} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2025-01-22 00:00:00+00:00
[2025-01-25T11:41:21.431-0300] {standard_task_runner.py:72} INFO - Started process 5776 to run task
[2025-01-25T11:41:21.437-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpuhbcijaj']
[2025-01-25T11:41:21.439-0300] {standard_task_runner.py:105} INFO - Job 18: Subtask twitter_datascience
[2025-01-25T11:41:21.569-0300] {task_command.py:467} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [running]> on host ANDERSON.
[2025-01-25T11:41:21.807-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TwitterDAG' AIRFLOW_CTX_TASK_ID='twitter_datascience' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-01-25T11:41:21.810-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-25T11:41:21.810-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-25T11:41:21.811-0300] {logging_mixin.py:190} INFO - Current task name:twitter_datascience state:running start_date:2025-01-25 14:41:21.344324+00:00
[2025-01-25T11:41:21.812-0300] {logging_mixin.py:190} INFO - Dag name:TwitterDAG and current dag run status:running
[2025-01-25T11:41:21.813-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T11:41:21.854-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T11:41:21.908-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-25T11:41:21.909-0300] {logging_mixin.py:190} INFO - Task start:2025-01-25 14:41:21.344324+00:00 end:2025-01-25 14:41:21.907216+00:00 duration:0.562892
[2025-01-25T11:41:21.910-0300] {logging_mixin.py:190} INFO - Task:<Task(TwitterOperator): twitter_datascience> dag:<DAG: TwitterDAG> dagrun:<DagRun TwitterDAG @ 2025-01-22 00:00:00+00:00: scheduled__2025-01-22T00:00:00+00:00, state:running, queued_at: 2025-01-25 14:39:40.963857+00:00. externally triggered: False>
[2025-01-25T11:41:21.911-0300] {logging_mixin.py:190} INFO - Failure caused by The conn_id `twitter_default` isn't defined
[2025-01-25T11:41:21.911-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_datascience, run_id=scheduled__2025-01-22T00:00:00+00:00, execution_date=20250122T000000, start_date=20250125T144121, end_date=20250125T144121
[2025-01-25T11:41:21.952-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T11:41:21.954-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task twitter_datascience (The conn_id `twitter_default` isn't defined; 5776)
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T11:41:22.023-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-25T11:41:22.065-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T11:41:22.096-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-25T12:18:40.115-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T12:18:40.146-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-25T12:18:40.162-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-25T12:18:40.163-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-25T12:18:40.209-0300] {taskinstance.py:2889} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2025-01-22 00:00:00+00:00
[2025-01-25T12:18:40.214-0300] {standard_task_runner.py:72} INFO - Started process 18505 to run task
[2025-01-25T12:18:40.230-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpo0dfpfr6']
[2025-01-25T12:18:40.232-0300] {standard_task_runner.py:105} INFO - Job 26: Subtask twitter_datascience
[2025-01-25T12:18:40.358-0300] {task_command.py:467} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [running]> on host ANDERSON.
[2025-01-25T12:18:40.534-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TwitterDAG' AIRFLOW_CTX_TASK_ID='twitter_datascience' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-01-25T12:18:40.536-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-25T12:18:40.537-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-25T12:18:40.538-0300] {logging_mixin.py:190} INFO - Current task name:twitter_datascience state:running start_date:2025-01-25 15:18:40.147552+00:00
[2025-01-25T12:18:40.539-0300] {logging_mixin.py:190} INFO - Dag name:TwitterDAG and current dag run status:running
[2025-01-25T12:18:40.540-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T12:18:40.585-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T12:18:40.635-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-25T12:18:40.636-0300] {logging_mixin.py:190} INFO - Task start:2025-01-25 15:18:40.147552+00:00 end:2025-01-25 15:18:40.635073+00:00 duration:0.487521
[2025-01-25T12:18:40.637-0300] {logging_mixin.py:190} INFO - Task:<Task(TwitterOperator): twitter_datascience> dag:<DAG: TwitterDAG> dagrun:<DagRun TwitterDAG @ 2025-01-22 00:00:00+00:00: scheduled__2025-01-22T00:00:00+00:00, state:running, queued_at: 2025-01-25 15:18:04.990607+00:00. externally triggered: False>
[2025-01-25T12:18:40.638-0300] {logging_mixin.py:190} INFO - Failure caused by The conn_id `twitter_default` isn't defined
[2025-01-25T12:18:40.638-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_datascience, run_id=scheduled__2025-01-22T00:00:00+00:00, execution_date=20250122T000000, start_date=20250125T151840, end_date=20250125T151840
[2025-01-25T12:18:40.680-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T12:18:40.682-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task twitter_datascience (The conn_id `twitter_default` isn't defined; 18505)
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T12:18:40.721-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-25T12:18:40.756-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T12:18:40.782-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-25T12:31:45.119-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T12:31:45.151-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-25T12:31:45.170-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-25T12:31:45.171-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-25T12:31:45.215-0300] {taskinstance.py:2889} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2025-01-22 00:00:00+00:00
[2025-01-25T12:31:45.222-0300] {standard_task_runner.py:72} INFO - Started process 25873 to run task
[2025-01-25T12:31:45.227-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpfxptw8sd']
[2025-01-25T12:31:45.229-0300] {standard_task_runner.py:105} INFO - Job 29: Subtask twitter_datascience
[2025-01-25T12:31:45.353-0300] {task_command.py:467} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [running]> on host ANDERSON.
[2025-01-25T12:31:45.545-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TwitterDAG' AIRFLOW_CTX_TASK_ID='twitter_datascience' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-01-25T12:31:45.548-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-25T12:31:45.549-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-25T12:31:45.550-0300] {logging_mixin.py:190} INFO - Current task name:twitter_datascience state:running start_date:2025-01-25 15:31:45.152862+00:00
[2025-01-25T12:31:45.552-0300] {logging_mixin.py:190} INFO - Dag name:TwitterDAG and current dag run status:running
[2025-01-25T12:31:45.553-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T12:31:45.603-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T12:31:45.689-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-25T12:31:45.690-0300] {logging_mixin.py:190} INFO - Task start:2025-01-25 15:31:45.152862+00:00 end:2025-01-25 15:31:45.688691+00:00 duration:0.535829
[2025-01-25T12:31:45.691-0300] {logging_mixin.py:190} INFO - Task:<Task(TwitterOperator): twitter_datascience> dag:<DAG: TwitterDAG> dagrun:<DagRun TwitterDAG @ 2025-01-22 00:00:00+00:00: scheduled__2025-01-22T00:00:00+00:00, state:running, queued_at: 2025-01-25 15:31:07.913128+00:00. externally triggered: False>
[2025-01-25T12:31:45.692-0300] {logging_mixin.py:190} INFO - Failure caused by The conn_id `twitter_default` isn't defined
[2025-01-25T12:31:45.693-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_datascience, run_id=scheduled__2025-01-22T00:00:00+00:00, execution_date=20250122T000000, start_date=20250125T153145, end_date=20250125T153145
[2025-01-25T12:31:45.732-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T12:31:45.734-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 29 for task twitter_datascience (The conn_id `twitter_default` isn't defined; 25873)
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T12:31:45.802-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-25T12:31:45.835-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T12:31:45.864-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-26T10:28:41.479-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T10:28:41.507-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-26T10:28:41.522-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-01-26T10:28:41.523-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-26T10:28:41.571-0300] {taskinstance.py:2889} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2025-01-22 00:00:00+00:00
[2025-01-26T10:28:41.577-0300] {standard_task_runner.py:72} INFO - Started process 4608 to run task
[2025-01-26T10:28:41.582-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpdw2sav3e']
[2025-01-26T10:28:41.584-0300] {standard_task_runner.py:105} INFO - Job 36: Subtask twitter_datascience
[2025-01-26T10:28:41.691-0300] {task_command.py:467} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-22T00:00:00+00:00 [running]> on host ANDERSON.
[2025-01-26T10:28:41.838-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TwitterDAG' AIRFLOW_CTX_TASK_ID='twitter_datascience' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-01-26T10:28:41.841-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T10:28:41.842-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T10:28:41.843-0300] {logging_mixin.py:190} INFO - Current task name:twitter_datascience state:running start_date:2025-01-26 13:28:41.508541+00:00
[2025-01-26T10:28:41.844-0300] {logging_mixin.py:190} INFO - Dag name:TwitterDAG and current dag run status:running
[2025-01-26T10:28:41.845-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T10:28:41.887-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-26T10:28:41.938-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-26T10:28:41.939-0300] {logging_mixin.py:190} INFO - Task start:2025-01-26 13:28:41.508541+00:00 end:2025-01-26 13:28:41.937059+00:00 duration:0.428518
[2025-01-26T10:28:41.940-0300] {logging_mixin.py:190} INFO - Task:<Task(TwitterOperator): twitter_datascience> dag:<DAG: TwitterDAG> dagrun:<DagRun TwitterDAG @ 2025-01-22 00:00:00+00:00: scheduled__2025-01-22T00:00:00+00:00, state:running, queued_at: 2025-01-26 13:28:05.238723+00:00. externally triggered: False>
[2025-01-26T10:28:41.941-0300] {logging_mixin.py:190} INFO - Failure caused by The conn_id `twitter_default` isn't defined
[2025-01-26T10:28:41.942-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_datascience, run_id=scheduled__2025-01-22T00:00:00+00:00, execution_date=20250122T000000, start_date=20250126T132841, end_date=20250126T132841
[2025-01-26T10:28:41.980-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T10:28:41.981-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 36 for task twitter_datascience (The conn_id `twitter_default` isn't defined; 4608)
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-26T10:28:42.036-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-26T10:28:42.070-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T10:28:42.091-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
