[2025-01-24T21:39:33.038-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T21:39:33.066-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-24T21:39:33.089-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-24T21:39:33.090-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-24T21:39:33.135-0300] {taskinstance.py:2889} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2025-01-19 00:00:00+00:00
[2025-01-24T21:39:33.140-0300] {standard_task_runner.py:72} INFO - Started process 18563 to run task
[2025-01-24T21:39:33.153-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2025-01-19T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpu8zrdq5r']
[2025-01-24T21:39:33.155-0300] {standard_task_runner.py:105} INFO - Job 3: Subtask twitter_datascience
[2025-01-24T21:39:33.321-0300] {task_command.py:467} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [running]> on host ANDERSON.
[2025-01-24T21:39:33.552-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TwitterDAG' AIRFLOW_CTX_TASK_ID='twitter_datascience' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-19T00:00:00+00:00'
[2025-01-24T21:39:33.555-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-24T21:39:33.556-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-24T21:39:33.557-0300] {logging_mixin.py:190} INFO - Current task name:twitter_datascience state:running start_date:2025-01-25 00:39:33.069726+00:00
[2025-01-24T21:39:33.558-0300] {logging_mixin.py:190} INFO - Dag name:TwitterDAG and current dag run status:running
[2025-01-24T21:39:33.559-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T21:39:33.621-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-24T21:39:33.817-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-24T21:39:33.818-0300] {logging_mixin.py:190} INFO - Task start:2025-01-25 00:39:33.069726+00:00 end:2025-01-25 00:39:33.816569+00:00 duration:0.746843
[2025-01-24T21:39:33.818-0300] {logging_mixin.py:190} INFO - Task:<Task(TwitterOperator): twitter_datascience> dag:<DAG: TwitterDAG> dagrun:<DagRun TwitterDAG @ 2025-01-19 00:00:00+00:00: scheduled__2025-01-19T00:00:00+00:00, state:running, queued_at: 2025-01-25 00:39:02.239735+00:00. externally triggered: False>
[2025-01-24T21:39:33.819-0300] {logging_mixin.py:190} INFO - Failure caused by The conn_id `twitter_default` isn't defined
[2025-01-24T21:39:33.820-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_datascience, run_id=scheduled__2025-01-19T00:00:00+00:00, execution_date=20250119T000000, start_date=20250125T003933, end_date=20250125T003933
[2025-01-24T21:39:33.865-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T21:39:33.867-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task twitter_datascience (The conn_id `twitter_default` isn't defined; 18563)
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-24T21:39:33.923-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-24T21:39:33.967-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-24T21:39:33.989-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-24T22:02:32.475-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T22:02:32.503-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-24T22:02:32.519-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-24T22:02:32.520-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-24T22:02:32.563-0300] {taskinstance.py:2889} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2025-01-19 00:00:00+00:00
[2025-01-24T22:02:32.567-0300] {standard_task_runner.py:72} INFO - Started process 3254 to run task
[2025-01-24T22:02:32.574-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2025-01-19T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmp7j5sxx5i']
[2025-01-24T22:02:32.576-0300] {standard_task_runner.py:105} INFO - Job 5: Subtask twitter_datascience
[2025-01-24T22:02:32.687-0300] {task_command.py:467} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [running]> on host ANDERSON.
[2025-01-24T22:02:32.834-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TwitterDAG' AIRFLOW_CTX_TASK_ID='twitter_datascience' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-19T00:00:00+00:00'
[2025-01-24T22:02:32.837-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-24T22:02:32.840-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-24T22:02:32.842-0300] {logging_mixin.py:190} INFO - Current task name:twitter_datascience state:running start_date:2025-01-25 01:02:32.504557+00:00
[2025-01-24T22:02:32.846-0300] {logging_mixin.py:190} INFO - Dag name:TwitterDAG and current dag run status:running
[2025-01-24T22:02:32.848-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T22:02:32.887-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-24T22:02:33.109-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-24T22:02:33.110-0300] {logging_mixin.py:190} INFO - Task start:2025-01-25 01:02:32.504557+00:00 end:2025-01-25 01:02:33.108393+00:00 duration:0.603836
[2025-01-24T22:02:33.110-0300] {logging_mixin.py:190} INFO - Task:<Task(TwitterOperator): twitter_datascience> dag:<DAG: TwitterDAG> dagrun:<DagRun TwitterDAG @ 2025-01-19 00:00:00+00:00: scheduled__2025-01-19T00:00:00+00:00, state:running, queued_at: 2025-01-25 01:02:06.295212+00:00. externally triggered: False>
[2025-01-24T22:02:33.111-0300] {logging_mixin.py:190} INFO - Failure caused by The conn_id `twitter_default` isn't defined
[2025-01-24T22:02:33.112-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_datascience, run_id=scheduled__2025-01-19T00:00:00+00:00, execution_date=20250119T000000, start_date=20250125T010232, end_date=20250125T010233
[2025-01-24T22:02:33.159-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T22:02:33.160-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task twitter_datascience (The conn_id `twitter_default` isn't defined; 3254)
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-24T22:02:33.269-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-24T22:02:33.305-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-24T22:02:33.337-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-25T00:10:41.528-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T00:10:41.558-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-25T00:10:41.576-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-25T00:10:41.577-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-25T00:10:41.630-0300] {taskinstance.py:2889} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2025-01-19 00:00:00+00:00
[2025-01-25T00:10:41.636-0300] {standard_task_runner.py:72} INFO - Started process 29402 to run task
[2025-01-25T00:10:41.642-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2025-01-19T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmps1ncplba']
[2025-01-25T00:10:41.647-0300] {standard_task_runner.py:105} INFO - Job 7: Subtask twitter_datascience
[2025-01-25T00:10:41.770-0300] {task_command.py:467} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [running]> on host ANDERSON.
[2025-01-25T00:10:41.955-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TwitterDAG' AIRFLOW_CTX_TASK_ID='twitter_datascience' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-19T00:00:00+00:00'
[2025-01-25T00:10:41.957-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-25T00:10:41.959-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-25T00:10:41.960-0300] {logging_mixin.py:190} INFO - Current task name:twitter_datascience state:running start_date:2025-01-25 03:10:41.559856+00:00
[2025-01-25T00:10:41.961-0300] {logging_mixin.py:190} INFO - Dag name:TwitterDAG and current dag run status:running
[2025-01-25T00:10:41.962-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T00:10:42.013-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T00:10:42.224-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-25T00:10:42.225-0300] {logging_mixin.py:190} INFO - Task start:2025-01-25 03:10:41.559856+00:00 end:2025-01-25 03:10:42.223944+00:00 duration:0.664088
[2025-01-25T00:10:42.226-0300] {logging_mixin.py:190} INFO - Task:<Task(TwitterOperator): twitter_datascience> dag:<DAG: TwitterDAG> dagrun:<DagRun TwitterDAG @ 2025-01-19 00:00:00+00:00: scheduled__2025-01-19T00:00:00+00:00, state:running, queued_at: 2025-01-25 03:10:04.037888+00:00. externally triggered: False>
[2025-01-25T00:10:42.227-0300] {logging_mixin.py:190} INFO - Failure caused by The conn_id `twitter_default` isn't defined
[2025-01-25T00:10:42.228-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_datascience, run_id=scheduled__2025-01-19T00:00:00+00:00, execution_date=20250119T000000, start_date=20250125T031041, end_date=20250125T031042
[2025-01-25T00:10:42.275-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T00:10:42.276-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task twitter_datascience (The conn_id `twitter_default` isn't defined; 29402)
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T00:10:42.390-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-25T00:10:42.431-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T00:10:42.469-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-25T11:38:23.579-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T11:38:23.605-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-25T11:38:23.620-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-25T11:38:23.621-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-25T11:38:23.661-0300] {taskinstance.py:2889} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2025-01-19 00:00:00+00:00
[2025-01-25T11:38:23.666-0300] {standard_task_runner.py:72} INFO - Started process 3957 to run task
[2025-01-25T11:38:23.671-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2025-01-19T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpo_9wxtwq']
[2025-01-25T11:38:23.674-0300] {standard_task_runner.py:105} INFO - Job 15: Subtask twitter_datascience
[2025-01-25T11:38:23.794-0300] {task_command.py:467} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [running]> on host ANDERSON.
[2025-01-25T11:38:23.977-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TwitterDAG' AIRFLOW_CTX_TASK_ID='twitter_datascience' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-19T00:00:00+00:00'
[2025-01-25T11:38:23.980-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-25T11:38:23.981-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-25T11:38:23.982-0300] {logging_mixin.py:190} INFO - Current task name:twitter_datascience state:running start_date:2025-01-25 14:38:23.606811+00:00
[2025-01-25T11:38:23.983-0300] {logging_mixin.py:190} INFO - Dag name:TwitterDAG and current dag run status:running
[2025-01-25T11:38:23.984-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T11:38:24.032-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T11:38:24.220-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-25T11:38:24.222-0300] {logging_mixin.py:190} INFO - Task start:2025-01-25 14:38:23.606811+00:00 end:2025-01-25 14:38:24.220192+00:00 duration:0.613381
[2025-01-25T11:38:24.222-0300] {logging_mixin.py:190} INFO - Task:<Task(TwitterOperator): twitter_datascience> dag:<DAG: TwitterDAG> dagrun:<DagRun TwitterDAG @ 2025-01-19 00:00:00+00:00: scheduled__2025-01-19T00:00:00+00:00, state:running, queued_at: 2025-01-25 14:37:46.781580+00:00. externally triggered: False>
[2025-01-25T11:38:24.223-0300] {logging_mixin.py:190} INFO - Failure caused by The conn_id `twitter_default` isn't defined
[2025-01-25T11:38:24.224-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_datascience, run_id=scheduled__2025-01-19T00:00:00+00:00, execution_date=20250119T000000, start_date=20250125T143823, end_date=20250125T143824
[2025-01-25T11:38:24.274-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T11:38:24.277-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task twitter_datascience (The conn_id `twitter_default` isn't defined; 3957)
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T11:38:24.407-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-25T11:38:24.442-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T11:38:24.462-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-25T11:50:18.617-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T11:50:18.646-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-25T11:50:18.661-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-25T11:50:18.662-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-25T11:50:18.705-0300] {taskinstance.py:2889} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2025-01-19 00:00:00+00:00
[2025-01-25T11:50:18.710-0300] {standard_task_runner.py:72} INFO - Started process 10060 to run task
[2025-01-25T11:50:18.717-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2025-01-19T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpqnlu30xr']
[2025-01-25T11:50:18.719-0300] {standard_task_runner.py:105} INFO - Job 21: Subtask twitter_datascience
[2025-01-25T11:50:18.829-0300] {task_command.py:467} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [running]> on host ANDERSON.
[2025-01-25T11:50:18.977-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TwitterDAG' AIRFLOW_CTX_TASK_ID='twitter_datascience' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-19T00:00:00+00:00'
[2025-01-25T11:50:18.979-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-25T11:50:18.980-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-25T11:50:18.981-0300] {logging_mixin.py:190} INFO - Current task name:twitter_datascience state:running start_date:2025-01-25 14:50:18.647132+00:00
[2025-01-25T11:50:18.982-0300] {logging_mixin.py:190} INFO - Dag name:TwitterDAG and current dag run status:running
[2025-01-25T11:50:18.983-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T11:50:19.022-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T11:50:19.067-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-25T11:50:19.069-0300] {logging_mixin.py:190} INFO - Task start:2025-01-25 14:50:18.647132+00:00 end:2025-01-25 14:50:19.066755+00:00 duration:0.419623
[2025-01-25T11:50:19.070-0300] {logging_mixin.py:190} INFO - Task:<Task(TwitterOperator): twitter_datascience> dag:<DAG: TwitterDAG> dagrun:<DagRun TwitterDAG @ 2025-01-19 00:00:00+00:00: scheduled__2025-01-19T00:00:00+00:00, state:running, queued_at: 2025-01-25 14:49:43.443662+00:00. externally triggered: False>
[2025-01-25T11:50:19.071-0300] {logging_mixin.py:190} INFO - Failure caused by The conn_id `twitter_default` isn't defined
[2025-01-25T11:50:19.072-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_datascience, run_id=scheduled__2025-01-19T00:00:00+00:00, execution_date=20250119T000000, start_date=20250125T145018, end_date=20250125T145019
[2025-01-25T11:50:19.114-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T11:50:19.115-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task twitter_datascience (The conn_id `twitter_default` isn't defined; 10060)
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T11:50:19.171-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-25T11:50:19.205-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T11:50:19.234-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-25T12:29:41.010-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T12:29:41.046-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-25T12:29:41.064-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [queued]>
[2025-01-25T12:29:41.065-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-25T12:29:41.113-0300] {taskinstance.py:2889} INFO - Executing <Task(TwitterOperator): twitter_datascience> on 2025-01-19 00:00:00+00:00
[2025-01-25T12:29:41.120-0300] {standard_task_runner.py:72} INFO - Started process 24416 to run task
[2025-01-25T12:29:41.133-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'TwitterDAG', 'twitter_datascience', 'scheduled__2025-01-19T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpo6pxathw']
[2025-01-25T12:29:41.135-0300] {standard_task_runner.py:105} INFO - Job 26: Subtask twitter_datascience
[2025-01-25T12:29:41.268-0300] {task_command.py:467} INFO - Running <TaskInstance: TwitterDAG.twitter_datascience scheduled__2025-01-19T00:00:00+00:00 [running]> on host ANDERSON.
[2025-01-25T12:29:41.444-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TwitterDAG' AIRFLOW_CTX_TASK_ID='twitter_datascience' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-19T00:00:00+00:00'
[2025-01-25T12:29:41.447-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-25T12:29:41.449-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-25T12:29:41.450-0300] {logging_mixin.py:190} INFO - Current task name:twitter_datascience state:running start_date:2025-01-25 15:29:41.047170+00:00
[2025-01-25T12:29:41.452-0300] {logging_mixin.py:190} INFO - Dag name:TwitterDAG and current dag run status:running
[2025-01-25T12:29:41.453-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T12:29:41.504-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T12:29:41.593-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-25T12:29:41.594-0300] {logging_mixin.py:190} INFO - Task start:2025-01-25 15:29:41.047170+00:00 end:2025-01-25 15:29:41.592820+00:00 duration:0.54565
[2025-01-25T12:29:41.595-0300] {logging_mixin.py:190} INFO - Task:<Task(TwitterOperator): twitter_datascience> dag:<DAG: TwitterDAG> dagrun:<DagRun TwitterDAG @ 2025-01-19 00:00:00+00:00: scheduled__2025-01-19T00:00:00+00:00, state:running, queued_at: 2025-01-25 15:29:05.506729+00:00. externally triggered: False>
[2025-01-25T12:29:41.596-0300] {logging_mixin.py:190} INFO - Failure caused by The conn_id `twitter_default` isn't defined
[2025-01-25T12:29:41.597-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=TwitterDAG, task_id=twitter_datascience, run_id=scheduled__2025-01-19T00:00:00+00:00, execution_date=20250119T000000, start_date=20250125T152941, end_date=20250125T152941
[2025-01-25T12:29:41.640-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T12:29:41.643-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task twitter_datascience (The conn_id `twitter_default` isn't defined; 24416)
Traceback (most recent call last):
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/operators/twitter_operator.py", line 33, in execute
    for pg in TwitterHook(end_time, start_time, query).run():
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/airflow_pipeline/hook/twitter_hook.py", line 58, in run
    session = self.get_conn()
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/providers/http/hooks/http.py", line 68, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/mnt/c/Users/ander/Desktop/airflow-spark/airflow-spark/curso2/ambientX/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `twitter_default` isn't defined
[2025-01-25T12:29:41.706-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-25T12:29:41.743-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T12:29:41.764-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
